### ISSUE TITLE
Suggestions for Improvements

### ISSUE THREAD

**Issue by timguo-ipfs** [ipfs-force-community/filscan-frontend#6]
### Suggestions for Improvements
1，added the data for **Total Pledge Collateral** in the whole network
2, the **Map** is outdated, the design can be optimized for better visual; add labels(number of participants) in each region
3, optimize the searching(node id), initial F can be auto-correct to f 
4, still cannot check newly created addresses like owner, worker and controller in filscan
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/72863918/128284547-22d0fd3c-09c9-442e-9197-d0a48c7b1a0f.png">
can we have a better map(better visual and more data)

**Comment by ritaA007** [comment]
Thanks @timguo-ipfs  for your suggestions. We'have put them into consideration and planned into our  schedule.
