### ISSUE TITLE
Add new feature: Storage Power Distribution 

### ISSUE THREAD

**Issue by timguo-ipfs** [ipfs-force-community/filscan-frontend#7]
**Storage Power Distribution**

<img width="761" alt="image" src="https://user-images.githubusercontent.com/72863918/129295867-fbf17b89-98a4-455d-b855-484248be1b4c.png">

**Background:**
so far we can check all nodes' status(power growth, rewards and so on) but for investors who want to to join this ecosystem need spend long time to do data analysis, one of the scenario is how to check about the current status of power distribution. 

**Execution plan:** 
At present, these ranges (from above chart) are captured manually. Is it possible to add a function directly on the browser?
Monthly variations of storage power (0-1, 2-10, 10-15, 50-100, 100+/PiB) and number of providers in different range. 

This will be really helpful for investors, storage providers and ecosystem partners to check about the current situation of Filecoin network.

**Comment by ritaA007** [comment]
Well noted, and will take it into our next upgrade. THX!
